name: Webmentions
 
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
 
jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
 
      - name: Install package
        run: npm install

      - name: Fetch webmentions
        run: node ./src/webmentions.js
 
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            Fetch webmentions
            skip-checks: true
        run: |
          git config user.email "heyjay@cctplus.dev"
          git config user.name "Jay Wilson"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/heyjaywilson/heyjaywilsoncom.git
          git checkout main
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin main)